# Generated by Django 5.2.6 on 2025-10-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchase_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
